global using Asp.Versioning;
global using Autofac;
global using Autofac.Extensions.DependencyInjection;
global using AutoMapper;
global using Consul;
global using Dapper;
global using Dapper.Extensions;
global using Dapper.Extensions.Caching;
global using Dapper.Extensions.Caching.Redis;
global using Elastic.Transport;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using FreeRedis;
global using Google.Protobuf.WellKnownTypes;
global using Grpc.Core;
global using Grpc.Core.Interceptors;
global using MediatR;
global using MediatR.Pipeline;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Hosting.Server.Features;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ApplicationModels;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.IdentityModel.Logging;
global using Microsoft.IdentityModel.Protocols.Configuration;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.Net.Http.Headers;
global using Microsoft.OpenApi.Models;
global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using MongoDB.Driver;
global using Muonroi.BuildingBlock.Contract.Interfaces;
global using Muonroi.BuildingBlock.External;
global using Muonroi.BuildingBlock.External.Attributes;
global using Muonroi.BuildingBlock.External.BearerToken;
global using Muonroi.BuildingBlock.External.Caching.Distributed.Redis;
global using Muonroi.BuildingBlock.External.Common;
global using Muonroi.BuildingBlock.External.Common.Constants;
global using Muonroi.BuildingBlock.External.Common.Enums;
global using Muonroi.BuildingBlock.External.Common.Models;
global using Muonroi.BuildingBlock.External.Common.Models.Requests.Login;
global using Muonroi.BuildingBlock.External.Common.Models.Requests.Registers;
global using Muonroi.BuildingBlock.External.Common.Models.Responses.Login;
global using Muonroi.BuildingBlock.External.Common.ValidationObject;
global using Muonroi.BuildingBlock.External.Controller.ActionFilters;
global using Muonroi.BuildingBlock.External.Controller.Conventions;
global using Muonroi.BuildingBlock.External.Default;
global using Muonroi.BuildingBlock.External.Entity;
global using Muonroi.BuildingBlock.External.Entity.DatabaseConfig;
global using Muonroi.BuildingBlock.External.Entity.EFConfig;
global using Muonroi.BuildingBlock.External.Entity.Identity;
global using Muonroi.BuildingBlock.External.Extensions;
global using Muonroi.BuildingBlock.External.ExternalApp.Delegatings;
global using Muonroi.BuildingBlock.External.Filters;
global using Muonroi.BuildingBlock.External.Helper;
global using Muonroi.BuildingBlock.External.Interfaces;
global using Muonroi.BuildingBlock.External.InternalEvents;
global using Muonroi.BuildingBlock.External.JsonConverter;
global using Muonroi.BuildingBlock.External.Middleware;
global using Muonroi.BuildingBlock.External.Models;
global using Muonroi.BuildingBlock.External.Polly;
global using Muonroi.BuildingBlock.External.Repositories;
global using Muonroi.BuildingBlock.External.Response;
global using Muonroi.BuildingBlock.External.SeedWorks;
global using Muonroi.BuildingBlock.External.Timing;
global using Muonroi.BuildingBlock.Internal;
global using Muonroi.BuildingBlock.Internal.Behaviours;
global using Muonroi.BuildingBlock.Internal.Infrastructure.Authorize;
global using Muonroi.BuildingBlock.Internal.Infrastructure.DelegatingHandlers;
global using Muonroi.BuildingBlock.Internal.Infrastructure.DI;
global using Muonroi.BuildingBlock.Internal.Startup.AutofacModules;
global using Newtonsoft.Json;
global using Polly;
global using RestEase;
global using Serilog;
global using Serilog.Debugging;
global using StackExchange.Redis;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using System.Collections.Concurrent;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Data;
global using System.Diagnostics;
global using System.Globalization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Linq.Expressions;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Reflection;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using BCrypts = BCrypt.Net.BCrypt;
global using CommandFlags = Dapper.CommandFlags;
global using Enum = System.Enum;
global using ICacheProvider = Muonroi.BuildingBlock.External.Caching.Distributed.Redis.ICacheProvider;
global using ILogger = Serilog.ILogger;
global using ISerilogLogger = Serilog.ILogger;
global using JsonIgnoreAttribute = System.Text.Json.Serialization.JsonIgnoreAttribute;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using Module = Autofac.Module;
global using NewtonsoftJsonSerializer = Newtonsoft.Json.JsonConvert;
global using RedisCacheProvider = Muonroi.BuildingBlock.External.Caching.Distributed.Redis.RedisCacheProvider;
global using Type = System.Type;
global using System.Runtime.Serialization;
